log_level: DEBUG
search_concurrency: 1
search_rate: 1
token_ttl: 1m
words_address: "words:8080"
update_address: "update:8080"
search_address: "search:8080"
api_server:
  address: ":8080"
  timeout: 5s